version: '3'
services:
  go:
    build:
      context: .
      dockerfile: DockerFile
    command: /bin/sh -c "go run ."
    stdin_open: true
    tty: true
    volumes:
      - ./src:/app
    ports:
      - 80:8080
    depends_on:
      - "db"
    container_name: go

  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    environment:
      MYSQL_ROOT_PASSWORD: "${ROOT_PASS}"
      MYSQL_DATABASE: "go_database"
      MYSQL_USER: "go_test"
      MYSQL_PASSWORD: "${PASS}"
      TZ: 'Asia/Tokyo'
    command: --default-authentication-plugin=mysql_native_password
    volumes:
#      - db-data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/conf.d
      - ./initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    restart: always
    container_name: mysql


volumes:
  db-data:
    driver: local